baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'adamwhiles dot com'
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1


[params]
title = "adamwhiles dot com"
description = "Portfolio for Adam Whiles"
favicon = "/favicon-32x32.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "adamwhiles dot com               "
  disableSearch = false
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Adam. Not Slim Shady :("
  subtitle = "I like to build, not rap"
  content = "A passionate husband, father, developer, creator and thinker. I like to make use of programming and scripting in various languages to create cool and useful stuff. I believe anything is possible with a positive attitude and grit (and money)."
  image = "adam.png"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/adamwhiles"

  [params.about]
  enable = true
  title = "About Me"
  image = "adam.png"
  content = """
  I am life longer learner and builder that is always busy working on some side project or learning some new technology. I am nearly finished with the Bachelors degree in Computer Science at WGU. Excited to continue learning and building cools things to test out new skills.

I am currently working on a project that will allow users to vote on learning resources for popular tech certification exams, such as Microsoft Azure exams."""
    [params.about.skills]
    enable = true
    title = "Here are a few languages and technologies I've been working with recently:"
    items = [ "Java", "JavaScript", "Python", "PowerShell", "Azure", "CI/CD Pipelines" ]



  [params.experience]
  enable = true

    [[params.experience.items]]
    company = "Afni"
    companyUrl = "http://"
    date = "Jan 2024 - present"

        [[params.experience.items.subs]]
        job = "Solutions Architect"
        date = "April 2023 - present"
        content = "asdasdasd"

        [[params.experience.items.subs]]
        job = "Senior Deployment Engineer"
        date = "August 2021 - 2023"

        [[params.experience.items.subs]]
        job = "Deployment Engineer"
        date = "February 2020 - 2021"

        [[params.experience.items.subs]]
        job = "Desktop Support Team Lead"
        date = "September 2009 - 2020"

  [params.education]
  enable = true
  index = false
    [[params.education.items]]
    title = "Bachelor of Science in Computer Science"
    date = "2024"
    
      [params.education.items.school]
      name = "Western Governors University"
      url = "https://wgu.edu"

    [[params.education.items]]
    title = "Associates of Science in Computer Science"
    date = "2022"

      [params.education.items.school]
      name = "University of the People"
      url = "https://uopeople.edu"

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "example"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"
    image = "/images/achievment.jpg"


  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "credibleDEV"
    content = "Blog site related to Linux, Homelab, Intune and Programming that I maintain."
    image = "/images/projects/credibledev.png"
    badges = [ "Hugo", "Hosted on Azure"]

      [params.projects.items.featured]
      name = "Site"
      link = "https://credibledev.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/adamwhiles/credibledev-blog"



  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Mail me"
  btnLink = "mailto:adam@adamwhiles.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = false
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/adamwhiles"
linkedin = "https://linkedin.com/in/adamwhiles"


  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
