name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: upload to blob
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob sync --account-name resumechallengetake2 --container '$web' --source './'

    - name: logout
      run: |
        az logout
      if: always()
